# coding: utf-8

"""
    API de Gestion de Contenu de Cours

    API REST pour gérer le contenu des cours en ligne, incluant les cours, séances, et l’organisation par module ou par semaine.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sances_api import SancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSancesApi(unittest.TestCase):
    """SancesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sances_api.SancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_courses_course_id_sessions_get(self):
        """Test case for courses_course_id_sessions_get

        Obtenir les séances d'un cours  # noqa: E501
        """
        pass

    def test_courses_course_id_sessions_post(self):
        """Test case for courses_course_id_sessions_post

        Créer une nouvelle séance pour un cours  # noqa: E501
        """
        pass

    def test_courses_course_id_sessions_session_id_put(self):
        """Test case for courses_course_id_sessions_session_id_put

        Mettre à jour une séance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
