# coding: utf-8

"""
    API de Gestion de Contenu de Cours

    API REST pour gérer le contenu des cours en ligne, incluant les cours, séances, et l’organisation par module ou par semaine.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cours_api import CoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCoursApi(unittest.TestCase):
    """CoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cours_api.CoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_courses_course_id_delete(self):
        """Test case for courses_course_id_delete

        Supprimer un cours  # noqa: E501
        """
        pass

    def test_courses_course_id_get(self):
        """Test case for courses_course_id_get

        Obtenir un cours spécifique  # noqa: E501
        """
        pass

    def test_courses_course_id_put(self):
        """Test case for courses_course_id_put

        Mettre à jour un cours  # noqa: E501
        """
        pass

    def test_courses_get(self):
        """Test case for courses_get

        Obtenir la liste des cours  # noqa: E501
        """
        pass

    def test_courses_post(self):
        """Test case for courses_post

        Créer un nouveau cours  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
